apps/accounts/urls.py
from django.urls import path
from .views import (ProfileView, MoneyView, RequestCreateView,
                                     RequestListView, RequestDetailView, RequestStatusView)

app_name = "accounts"

urlpatterns = [
    path("profile/", ProfileView.as_view(), name='profile'),
    path("profile/<int:id>/", ProfileView.as_view(), name='profile'),
    path("exchange/", MoneyView.as_view(), name="exchange-money"), 

    path("add-request/", RequestCreateView.as_view(), name="add-request"),
    path('request-list/', RequestListView.as_view(), name="request-list"),
    path('request-detail/<str:token>/', RequestDetailView.as_view(), name="request-detail"),
    path('request-status/<int:request_token>/<str:status>/', RequestStatusView.as_view(), name="request-status")
]

apps/restaurant/urls.py
from django.urls import path
from .views.restaurant import (RegisterRestaurantView,
                                     RestaurantProfileView, DashBoardRestaurant, RestaurantRequestListView,
                                     RestaurantRequestStatusView, RestaurantDeleteView, RestaurantOrderList, ItemPreparedView, 
                                     OrderArrived)
from .views.food import (FoodCreateView, FoodDetailView, FoodListView, FoodDeleteView)

app_name = "restaurant"


urlpatterns = [
    path("", DashBoardRestaurant.as_view(), name="restaurant-dashboard"),
    path("foods/", FoodListView.as_view(), name="food-list"),

    path("register/", RegisterRestaurantView.as_view(), name="register-restaurant"),
    path("add-food/", FoodCreateView.as_view(), name="add-food"),
    path("delete-food/<str:token>/", FoodDeleteView.as_view(), name="delete-food"),
    path("requests/", RestaurantRequestListView.as_view(), name='restaurant-request-list'),
    path('restaurant-status/<str:restaurant_token>/<str:status>/', RestaurantRequestStatusView.as_view(), name="restaurant-status"),
    
    path("delete-restaurant/<str:token>/", RestaurantDeleteView.as_view(), name="delete-restaurant"),

    path("food-detail/<str:token>/", FoodDetailView.as_view(), name="food-detail"),
    path("profile/<str:token>/", RestaurantProfileView.as_view(), name="restaurant-profile"),

    path('orders/', RestaurantOrderList.as_view(), name= "restaurant-orders"),
    path('item-prepared/<int:id>/', ItemPreparedView.as_view(), name="item-prepared"),
    path('order-arrived/<int:order_id>/', OrderArrived.as_view(), name="food-arrived"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import login, logout, signup


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),

    path("login/", login, name="account_login"), 
    path("logout/", logout, name="account_logout"), 
    path("signup/", signup, name="account_signup"), 

    path('', include("customer.urls")),
    path('restaurant/', include("restaurant.urls")),

    path('ratings/', include('star_ratings.urls', namespace='ratings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.customer.views.handler404'
handler500 = 'apps.customer.views.handler500'

apps/restaurant/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating
from django.urls import reverse
from accounts.models import User
from accounts.utils.validators import validate_file_size
from accounts.utils.token_generator import random_number


class Restaurant(models.Model):
    
    class Status(models.TextChoices):
        '''Restaurant Status'''
        PENDING = ("p", "pending")
        ACCEPTED = ("a", "Accepted")
        REJECTED = ("r", "Rejected")
        BLOCKED = ("b", "Blocked")

    name = models.CharField(max_length= 50)    
    
    picture = models.ImageField(upload_to= "restaurant/profile",
                                    validators=[validate_file_size,])
    description = models.TextField()

    country = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    detailed_address = models.CharField(max_length=120, blank=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="restaurant")

    email = models.EmailField(max_length=70, unique=True)

    status = models.CharField(max_length=1, choices=Status.choices, default=Status.PENDING)
    token = models.CharField(max_length=15, default=random_number)
    date_registered = models.DateTimeField(auto_now_add=True)

    ratings = GenericRelation(Rating)

    @property
    def is_accepted(self):
        return bool(self.status == "a")
    
    @property
    def is_blocked(self):
        return bool(self.status == "b")

    def get_absolute_url(self):
        return reverse("restaurant:restaurant-profile",
                             kwargs={"id" : self.id, "token" : self.token})

    def __str__(self):
        return  self.name
    



class Food(models.Model):
    name = models.CharField(max_length= 120)
    picture = models.ImageField(upload_to="foods/")

    description = models.TextField()
    category = models.ManyToManyField("Category", related_name="food_category")
    provider = models.ForeignKey(Restaurant, on_delete=models.CASCADE, blank=True,
                 related_name="foods")

    inventory = models.PositiveIntegerField(default=0)

    price = models.PositiveIntegerField()

    token = models.CharField(max_length=15, default=random_number)

    ratings = GenericRelation(Rating)

    @property
    def is_available(self):
        return bool(self.inventory > 0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return  reverse("restaurant:food-detail", args=[self.token])
        

class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

apps/restaurant/forms.py
from django import forms
from restaurant.models import Restaurant, Food

class RestaurantForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(RestaurantForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Restaurant
        fields = ("name", "picture", "description", "country", "city",
                 "detailed_address", "email")

    def save(self, commit=True):
        form = super().save(commit=False)
        form.owner = self.user
        form.save()
        return form


class FoodForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.restaurants = kwargs.pop('restaurants', None)
        super(FoodForm, self).__init__(*args, **kwargs)
        self.fields["provider"].queryset = self.restaurants


    class Meta:
        model = Food
        fields = ("name", "picture", "description", "category", 
                "inventory", "price", "provider")

    def save(self, commit=True):
        form =  super().save(commit=False)
        form.save()
        return form

apps/restaurant/views/food.py
from django.views.generic import  FormView, UpdateView, ListView, DeleteView
from django.shortcuts import  redirect, get_object_or_404
from django.contrib import  messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy

from restaurant.models import  Food
from customer.views import Order, OrderItem
from restaurant.mixins import AddFoodMixin
from restaurant.forms import FoodForm

class FoodCreateView(LoginRequiredMixin, AddFoodMixin, FormView):
    '''
        Add food to database
    '''

    form_class = FoodForm
    template_name = "food/add-food.html"

    def form_valid(self, form):
        form.save()
        form.save_m2m()
        messages.success(self.request, "food created successfully", "success")
        return  redirect("restaurant:food-list")
    

    def form_invalid(self, form):
        messages.success(self.request, "Sth went wrong with your information", "danger")
        return  redirect("restaurant:food-list")


    def get_form_kwargs(self, **kwargs):
        kwargs = super(FoodCreateView, self).get_form_kwargs()
        kwargs['restaurants'] = self.request.user.restaurant.filter(status="a")
        return kwargs
        


class FoodDetailView(UpdateView):
    '''
        Detail page for foods
        Also update page for provider
    '''

    template_name = "food/food-detail.html"
    fields = ["name", "description", "picture", "inventory", "price"]
    context_object_name = "food"

    def get_object(self):
        return  get_object_or_404(Food, token=self.kwargs["token"])
    
    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user == self.get_object().provider.owner:
                super().post(request, *args, **kwargs)
                messages.success(request, "Food updated successfuly.", "success")    
                return redirect("restaurant:food-detail", token=self.get_object().token)

            messages.success(request, "You are not this foods provider.", "danger")    
            return redirect("restaurant:food-detail", token=self.get_object().token)
                
        
        messages.success(request, "Unknown users cannot update this object.", "danger")
        return redirect("restaurant:food-detail", token=self.get_object().token)
        


class FoodListView(LoginRequiredMixin, ListView):
    '''
        List of all foods of a restaurant
    '''
    template_name = "food/food-list.html"
    context_object_name = "foods"

    def get_queryset(self):
        return Food.objects.filter(provider__in=self.request.user.restaurant.all())


class FoodDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "food/food-delete.html"
    success_url = reverse_lazy("restaurant:food-list")
    def dispatch(self, request, *args, **kwargs):
        unprepared_order = OrderItem.objects.filter(Q(item=self.get_object()) & Q(order__is_paid=True) &
                                    ~Q(prepared=True))
        if unprepared_order.exists():
            messages.success(self.request, "You have orders that you havnt prepared them.", "danger")
            return redirect("restaurant:food-detail", token=self.get_object().token)

        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        return get_object_or_404(Food,token=self.kwargs["token"], 
                                    provider__in=self.request.user.restaurant.filter(status="a"))

    def post(self, request, *args, **kwargs):
        
        messages.success(self.request, "food deleted successfully", "success")
        return super().post(request, *args, **kwargs)

apps/restaurant/views/food_views.py
from django.views.generic import  FormView, UpdateView, DetailView, ListView
from django.shortcuts import  redirect, get_object_or_404
from django.template.defaultfilters import slugify
from django.contrib import  messages
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from restaurant.models import  Food
from restaurant.mixins import AddFoodMixin, FoodUpdateMixin
from restaurant.forms import FoodForm

class CreateFoodView(LoginRequiredMixin, AddFoodMixin, FormView):
    '''
        Create a new food
    '''

    form_class = FoodForm
    template_name = "food/create-food.html"

    def form_valid(self, form):
        form_data = self.form_class(self.request.POST, self.request.FILES)
        form_data = form.save(commit=False)
        form_data.provider = self.request.user.restaurant
        form_data.slug = slugify(form_data.name) + slugify(form_data.provider)
        form_data.save()
        form.save_m2m()
        messages.success(self.request, "food created successfully")
        return  redirect("restaurant:list-food")


class UpdateFoodView(LoginRequiredMixin, FoodUpdateMixin, UpdateView):
    '''
        Update foods status or price
    '''
    template_name = "food/update-food.html"


    fields = ["inventory","price", "is_available"]

    def get_object(self):
        return get_object_or_404(Food, pk=self.kwargs["pk"],
                                 slug=self.kwargs["slug"], provider=self.request.user.restaurant)

    def get_success_url(self):
        return reverse("restaurant:list-food")

class DetailFoodView(DetailView):
    '''
        Detail page for foods
    '''
    template_name = "food/detail-food.html"

    def get_object(self):
        return  get_object_or_404(Food, pk=self.kwargs["pk"],
                          slug=self.kwargs["slug"])
class ListFoodView(ListView):
    '''
        List of all foods of a restaurant
    '''
    template_name = "food/list-food.html"
    context_object_name = "foods"

    def get_queryset(self):
        return Food.objects.filter(provider= self.request.user.restaurant)

apps/restaurant/templates/restaurant/dashboard-restaurant.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}DashBord{% endblock title %}

{% block body %}
<h2>DashBord</h2> <hr>
<h4>You have added {{food}} foods.</h4>
<a href="{% url 'restaurant:food-list' %}">List of foods</a>
<br><hr>
<h4><a href="{% url 'restaurant:restaurant-orders' %}">Orders</a> </h4>
<hr>

<h4>Registered Restaurants:</h4>
{% for restaurant in restaurants %}
    <a href="{% url 'restaurant:restaurant-profile' restaurant.token%}"><h4>{{ restaurant.name }}</h4></a> <br>
{% endfor %}
<hr>

{% endblock body %}

apps/restaurant/templates/restaurant/orders-restaurant.html
{% extends '_base.html' %}
{% block title %}Orders{% endblock title %}

{% block body %}

{% for order in orders %}
   <div id="accordion">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{order.order}}
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        <a href="{% url 'restaurant:food-detail' order.item.token %}">{{ order.item }}</a> | {{ order.quantity }}
          <br><br>
          <a class="btn btn-success" href="{% url 'restaurant:item-prepared' order.id %}">Prepared</a>
      </div>
    </div>
  </div>
</div>
{% empty %}
  <h3>No order available</h3>
{% endfor %}
{% endblock body %}

apps/restaurant/templates/restaurant/register-restaurant.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register Restaurant{% endblock title %}

{% block body %}
<h2>Register Restaurant</h2><br>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <hr>
    {{form.name | as_crispy_field }}
    {{form.description | as_crispy_field }}
    {{form.email | as_crispy_field }}
    <h6>Profile picture</h6>
    {{form.picture}} <br><br>
    <hr><h4>Address</h4><br>
    {{form.country | as_crispy_field }}
    {{form.city | as_crispy_field }}
    {{form.detailed_address | as_crispy_field }}
    
    <br><button class="btn btn-success" type="submit">Register</button>
    <br><br>
</form>
{% endblock body %}

apps/restaurant/templates/restaurant/restaurant-delete.html
{% extends '_base.html' %}

{% block title %}Delete Restaurant{% endblock title %}

{% block body %}
<h2>Are you sure you wanna delete "{{ restaurant.name }}"??</h2><br>

<form method="post">{% csrf_token %}
    
    <br><button class="btn btn-danger" type="submit">Delete</button>
    <br><br>
</form>
{% endblock body %}

apps/restaurant/templates/restaurant/restaurant-profile.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{object.name}}'s Profile{% endblock title %}

{% block body %}
<h1 style="display: inline-block;">{{object.name}}</h1>
<img src="{{object.picture.url}}" style="width:5cm; float: right;">
<hr>
<p>{{object.description}}</p>
<hr>
<h4>Location</h4>
<h5>{{object.country}} - {{object.city}} - {{object.detailed_address}}</h5>
<hr>
<h4>Email</h4>
<h5>{{object.email}}</h5>
<hr>
<small>owner: {{object.owner}}</small>

{% if request.user.is_admin and request.user != object.owner and object.status == 'p'%}
    <hr>    
        <a class="btn btn-success" href="{% url 'restaurant:restaurant-status' object.token "a" %}">Accept</a>
        <a class="btn btn-danger" href="{% url 'restaurant:restaurant-status' object.token "d" %}">Decline</a>
        <a class="btn btn-secondary" href="{% url 'restaurant:restaurant-status' object.token "b" %}">Block</a>
        <hr>
{% endif %}

{% if request.user == object.owner and object.status == 'p' %}
<hr> <br><h3>Update:</h3><br>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Update</button>
</form>

{% endif %}

{% if request.user == object.owner %}
    <hr>
    <a class="btn btn-danger" href="{% url 'restaurant:delete-restaurant' object.token %}">Delete restaurant</a>
{% endif %}
{% endblock body %}

apps/restaurant/templates/restaurant/restaurant-register.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register Restaurant{% endblock title %}

{% block body %}
<h2>Register Restaurant</h2><br>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <hr>
    {{form.name | as_crispy_field }}
    {{form.description | as_crispy_field }}
    {{form.email | as_crispy_field }}
    <h6>Profile picture</h6>
    {{form.picture}} <br><br>
    <hr><h4>Address</h4><br>
    {{form.country | as_crispy_field }}
    {{form.city | as_crispy_field }}
    {{form.detailed_address | as_crispy_field }}
    
    <br><button class="btn btn-success" type="submit">Register</button>
    <br><br>
</form>
{% endblock body %}

apps/restaurant/templates/restaurant/restaurant-request-list.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Request List{% endblock title %}

{% block body %}
<h2>Restaurant Request List</h2><a href="{% url 'restaurant:register-restaurant' %}">New request</a>
 <hr>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">User</th>
        <th scope="col">Status</th>
        <th scope="col">Restaurant name</th>
        <th scope="col">Detail</th>
      </tr>
    </thead>
    <tbody>
      {% for request in requests %}
        <tr>
            <th scope="row">1</th>
            <td><a href="{% url 'accounts:profile' request.owner.userid %}">{{ request.owner }}</a></td>
            <td>{{ request.get_status_display  }}</td>
            <td>{{ request.name }}</td>
            <td><center><a class="btn btn-secondary" href="{% url 'restaurant:restaurant-profile' request.token %}">
                          {{ request.token }}</a></center></td>
        </tr>
      {% empty %}
        <h3>No request available.</h3>
      {% endfor %}
    </tbody>
  </table>

{% endblock body %}